jobs:
  - name: 'bronze_full'
    type: 'full'
    tables: 
    - table_name: 'assets'
      input_format: 'json'
      catalog: 'bronze'
      schema: 'brapi'
    
    - table_name: 'tickers'
      input_format: 'json'
      catalog: 'bronze'
      schema: 'brapi'
    
  - name: 'bronze_cdc'
    type: 'cdc'
    tables:
      - table_name: 'tickers'
        input_format: 'json'
        catalog: 'bronze'
        schema: 'brapi'
        
      - table_name: 'assets'
        input_format: 'json'
        catalog: 'bronze'
        schema: 'brapi'

    
